# Nginx configuration file

events {
    # Required events block for Nginx
}

http {

    server {

        # Listen for incoming HTTP requests on port 80
        listen 80;

        location / {

            # Forward incoming requests to the Node.js application
            # "node-app" is the Docker Compose service name
            proxy_pass http://node-app:4000;
        }
    }
}